dist: trusty
language: python
python: 3.5
install:
  - pip install -e .
  - pip install -r requirements.txt
before_script:
  - cp test_config_travis.py /tmp/kuyruk_config.py
script:
  - flake8 kuyruk/
  - mypy kuyruk/
  - pytest -v --cov=kuyruk tests/
after_success:
  - pip install coveralls
  - coverage combine
  - coveralls
services:
  - rabbitmq
before_deploy:
  - echo "$TRAVIS_TAG" > VERSION
deploy:
  on:
    repo: cenkalti/kuyruk
    tags: true
  skip_cleanup: true
  provider: pypi
  user: cenkalti
  password:
    secure: WISXo+4rni+S51yz6YBiv+Nee8L+GEWb10chnAOkqobnk4IV8p87fyH6hlD5WwzdRUJmvnmvgLm8xni0vfGmQOAwfyCFdDMWdXubL74SRLjG0g7cKWzS8GumlgA+1m2tHDYv2fIFOjgrF7KKX3GXhFUlv8ei7RyYd8+ecLV6L/Y=
